[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rust-rag"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
llama-index = ">=0.11.22,<0.12"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
sentence-transformers = ">=3.2.1,<4"
ipykernel = ">=6.29.5,<7"
black = ">=24.10.0,<25"
chromadb = ">=0.5.18,<0.6"
transformers = ">=4.46.2,<5"
tqdm = ">=4.67.0,<5"
einops = ">=0.8.0,<0.9"
arize-phoenix = ">=5.7.0,<6"
mlflow = ">=2.17.2,<3"

[pypi-dependencies]
llama-index-llms-ollama = ">=0.3.6, <0.4"
llama-index-embeddings-huggingface = ">=0.3.1, <0.4"
llama-index-vector-stores-chroma = ">=0.3.0, <0.4"
