[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rust-rag"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
ipykernel = ">=6.29.5,<7"
black = ">=24.10.0,<25"
chromadb = ">=0.5.18,<0.6"
transformers = ">=4.46.2,<5"
tqdm = ">=4.67.0,<5"
einops = ">=0.8.0,<0.9"
arize-phoenix = ">=5.7.0,<6"
mlflow = ">=2.17.2,<3"

[pypi-dependencies]
llama-index-finetuning = ">=0.1.7, <0.2"
llama-index-llms-ollama = ">=0.2.2, <0.3"
llama-index-embeddings-huggingface = ">=0.2.3, <0.3"
llama-index-vector-stores-chroma = ">=0.1.10, <0.2"
llama-index-retrievers-bm25 = ">=0.2.2, <0.3"
llama-index-core = ">=0.10.68.post1, <0.11"
llama-index = ">=0.10.68, <0.11"
